[package]
name = "hasty"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
shellwords = "1.1.0"
nix = "0.15.0"
json = "0.12.4"